- job:
    description: Operator integration tests
    name: zuul-operator-functional
    abstract: true
    run: playbooks/zuul-operator-functional/run.yaml
    post-run: playbooks/zuul-operator-functional/post.yaml
    requires: docker-image
    vars:
      # We disable userland-proxy to enable scheduler deployement to connect to the gearman service
      # see: https://github.com/eclipse/che/issues/8134
      docker_userland_proxy: false

- job:
    description: Operator integration tests with Kubernetes
    name: zuul-operator-functional-k8s
    parent: zuul-operator-functional
    pre-run: playbooks/zuul-operator-functional/pre-k8s.yaml
    nodeset: ubuntu-bionic
    vars:
      namespace: 'default'

- job:
    description: Image and buildset registry job
    name: zuul-operator-build-image
    parent: opendev-build-docker-image
    allowed-projects: zuul/zuul-operator
    vars:
      zuul_work_dir: "{{ zuul.projects['opendev.org/zuul/zuul-operator'].src_dir }}"
      docker_images:
        - context: .
          dockerfile: build/Dockerfile
          repository: zuul/zuul-operator

- project:
    check:
      jobs:
        - zuul-operator-build-image
        - zuul-operator-functional-k8s:
            dependencies: zuul-operator-build-image
    gate:
      jobs:
        - zuul-operator-build-image
        - zuul-operator-functional-k8s:
            dependencies: zuul-operator-build-image
