apiVersion: operator.zuul-ci.org/v1alpha1
kind: Zuul
metadata:
  name: zuul
spec:
  executor:
    count: 1
    ssh_key:
      secretName: executor-ssh-key
  merger:
    count: 1
  scheduler:
    config:
      secretName: zuul-yaml-conf
  launcher:
    config:
      secretName: nodepool-yaml-conf
  connections:
    gits:
      - baseurl: https://opendev.org
        name: opendev.org
  external_config:
    kubernetes:
      secretName: nodepool-kube-config
      key: kube.config
