apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zuulservices.operator.zuul-ci.org
spec:
  group: operator.zuul-ci.org
  names:
    kind: ZuulService
    listKind: ZuulServiceList
    plural: zuulservices
    singular: zuulservice
    shortNames:
      - zuul
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
