apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zuul-operator
  template:
    metadata:
      labels:
        name: zuul-operator
    spec:
      serviceAccountName: zuul-operator
      containers:
        - name: manager
          args:
            - "--enable-leader-election"
            - "--leader-election-id=zuul-operator"
          env:
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: "docker.io/zuul/zuul-operator"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: /readyz
              port: 6789
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 10
