apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zuul-operator
  template:
    metadata:
      labels:
        name: zuul-operator
    spec:
      serviceAccountName: zuul-operator
      containers:
        - name: ansible
          command:
          - /uid_entrypoint
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # TODO: use a public name
          image: "zuul/zuul-operator"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "zuul/zuul-operator"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "zuul-operator"
      volumes:
        - name: runner
          emptyDir: {}
