- name: start kubernetes and install all dependencies
  hosts: all
  roles:
    - role: clear-firewall
    - role: ensure-pip
    - role: ensure-podman
    - role: ensure-kubernetes
      vars:
        minikube_dns_resolvers:
          - '1.1.1.1'
          - '8.8.8.8'
        ensure_kubernetes_minikube_addons:
          - ingress
    - role: use-buildset-registry
      buildset_registry_docker_user: root
  post_tasks:
    - name: Install openshift client for k8s tasks
      command: python3 -m pip install --user openshift
    - name: Install websocket
      become: true
      package:
        name:
          - python3-websocket
          - jq
    - name: check kubernetes connection
      command: timeout 10s kubectl get pods
      register: _api_ready
      until: _api_ready.rc == 0
      retries: 6
      delay: 10
