- name: start kubernetes and install all dependencies
  hosts: all
  roles:
    - role: clear-firewall
    - role: ensure-pip
    - role: ensure-podman
    - role: ensure-kubernetes
      vars:
        minikube_dns_resolvers:
          - '1.1.1.1'
          - '8.8.8.8'
        kubernetes_runtime: podman
        ensure_kubernetes_minikube_addons:
          - ingress
        ensure_kubernetes_bin_path: /usr/local/bin
    - role: use-buildset-registry
  post_tasks:
    - name: Install ansible requirements
      become: true
      package:
        name:
          - python3-kubernetes
          - python3-yaml
          - python3-openshift
          - python3-websocket
          - python3-jsonpatch
          - jq
    - name: check kubernetes connection
      command: timeout 10s kubectl get pods
      register: _api_ready
      until: _api_ready.rc == 0
      retries: 6
      delay: 10
