- name: install and start zuul operator
  hosts: all
  tasks:
    - name: Setup CRD
      command: make install
      args:
        chdir: "{{ zuul.projects['opendev.org/zuul/zuul-operator'].src_dir }}"

    - name: Create required secret
      include_tasks: ./tasks/create_test_secrets.yaml

    - name: Wait for operator deployment
      command: timeout 8m kubectl rollout status deployment/zuul-operator

    - name: Deploy CR
      include_tasks: tasks/apply_cr.yaml
      vars:
        spec:
          executor:
            count: 1
            sshkey:
              secretName: executor-ssh-key
          merger:
            count: 1
          scheduler:
            config:
              secretName: zuul-yaml-conf
          launcher:
            config:
              secretName: nodepool-yaml-conf
          connections:
            opendev.org:
              driver: git
              baseurl: https://opendev.org
          externalConfig:
            kubernetes:
              secretName: nodepool-kube-config
          registry:
            count: 1
          preview:
            count: 1

    - name: Wait for services
      include_tasks: ./tasks/wait_services.yaml

    - name: Test the cert-manager
      include_tasks: ./tasks/test_cert_manager.yaml

    # TODO: implement
    # - name: Test the registry
    #   include_tasks: ./tasks/test_registry.yaml
