# Render kubernetes resources using:
# INPUT=$(yaml-to-dhall "(./conf/zuul/input.dhall).Input.Type" < playbooks/files/cr_spec.yaml)
# dhall-to-yaml --explain <<< "(./conf/zuul/resources.dhall ($INPUT)).Components.Zuul.Scheduler"
# Or
# dhall-to-yaml --explain <<< "(./conf/zuul/resources.dhall ($INPUT)).List"

executor:
  count: 1
  ssh_key:
    secretName: executor-ssh-key
merger:
  count: 1
scheduler:
  config:
    secretName: zuul-yaml-conf
registry:
  count: 0
launcher:
  config:
    secretName: nodepool-yaml-conf
connections:
  gits:
    - baseurl: https://opendev.org
      name: opendev.org
externalConfig:
  kubernetes:
    secretName: nodepool-kube-config
    key: kube.config

jobVolumes:
  - context: trusted
    access: ro
    path: /authdaemon/token
    dir: /authdaemon
    volume:
      name: gcp-auth
      hostPath:
        path: /var/authdaemon/executor
        type: DirectoryOrCreate

# extra
name: zuul
web: {}
