---
- name: Scheduler Deployment
  vars:
    deployment_name: scheduler
    deployment_ports:
      - containerPort: 4730
        protocol: "TCP"
    deployment_config: "{{ zuul_configmap_name }}-scheduler"
  include_tasks: "./create_deployment.yaml"
  register: sched_deployment

- name: Scheduler service
  vars:
    service_name: scheduler
    service_ports:
      - name: "gearman"
        port: 4730
        protocol: TCP
  include_tasks: "./create_service.yaml"

- name: Reload scheduler
  include_tasks: "./reload_scheduler.yaml"
  when:
    - sched_deployment is not changed
    - tenant_config_updated

- name: Merger Deployment
  vars:
    deployment_name: merger
    deployment_replicas: "{{ merger.instances }}"
  include_tasks: "./create_deployment.yaml"

- name: Executor Deployment
  vars:
    deployment_name: executor
    deployment_replicas: "{{ executor.instances }}"
  include_tasks: "./create_deployment.yaml"

- name: Web Deployment
  vars:
    deployment_name: web
    deployment_replicas: "{{ web.instances }}"
    deployment_ports:
      - containerPort: 9000
        protocol: "TCP"
  include_tasks: "./create_deployment.yaml"

- name: Web Service
  vars:
    service_name: web
    service_ports:
      - name: "web"
        port: 80
        protocol: TCP
        targetPort: 9000
  include_tasks: "./create_service.yaml"
