---
- name: Nodepool Deployment
  vars:
    deployment_name: launcher
    deployment_conf: "{{ launcher }}"
  include_tasks: "./create_nodepool_deployment.yaml"

- name: Save queue
  include_tasks: "./queue_save.yaml"
  when:
    - scheduler_config is changed
    - zuul_scheduler_pod

- name: Scheduler Deployment
  vars:
    deployment_name: scheduler
    deployment_ports:
      - containerPort: 4730
        protocol: "TCP"
    deployment_config: "{{ zuul_configmap_name }}-scheduler"
    deployment_conf:
      min: 1
  include_tasks: "./create_deployment.yaml"
  register: sched_deployment

- name: Scheduler service
  vars:
    service_name: scheduler
    service_ports:
      - name: "gearman"
        port: 4730
        protocol: TCP
  include_tasks: "./create_service.yaml"

- name: Wait for Service
  set_fact:
    gearman_service: "{{ lookup('k8s', api_version='v1', kind='Service', namespace=namespace, resource_name=zuul_cluster_name + '-scheduler') }}"
  until: gearman_service
  retries: 5
  delay: 10

- name: Reload scheduler
  include_tasks: "./reload_scheduler.yaml"
  when:
    - sched_deployment is not changed
    - tenant_config_updated

- name: Merger Deployment
  vars:
    deployment_name: merger
    deployment_conf: "{{ merger }}"
  include_tasks: "./create_deployment.yaml"

- name: Executor Deployment
  vars:
    deployment_name: executor
    deployment_conf: "{{ executor }}"
  include_tasks: "./create_deployment.yaml"

- name: Web Deployment
  vars:
    deployment_name: web
    deployment_conf: "{{ web }}"
    deployment_ports:
      - containerPort: 9000
        protocol: "TCP"
  include_tasks: "./create_deployment.yaml"

- name: Web Service
  vars:
    service_name: web
    service_ports:
      - name: "web"
        port: 80
        protocol: TCP
        targetPort: 9000
  include_tasks: "./create_service.yaml"

- name: Load queue
  include_tasks: "./queue_load.yaml"
  when:
    - scheduler_config is changed
    - zuul_scheduler_pod
