- name: install and start zuul operator
  hosts: all

  tasks:
    - name: Set Operator SDK Release Version fact
      set_fact:
        RELEASE_VERSION: v0.8.1

    - name: Download Operator SDK Binary Release to Path
      become: yes
      get_url:
        url: https://github.com/operator-framework/operator-sdk/releases/download/{{ RELEASE_VERSION }}/operator-sdk-{{ RELEASE_VERSION }}-x86_64-linux-gnu
        dest: /usr/local/bin/operator-sdk
        mode: a+x

    - name: Build operator
      command: operator-sdk build zuul/zuul-operator
      args:
        chdir: "{{ zuul.projects['opendev.org/zuul/zuul-operator'].src_dir }}"

    - name: Setup CRD
      command: kubectl create -f deploy/crds/zuul-ci_v1alpha1_zuul_crd.yaml
      args:
        chdir: "{{ zuul.projects['opendev.org/zuul/zuul-operator'].src_dir }}"

    - name: Setup rbac
      command: kubectl create -f deploy/rbac.yaml
      args:
        chdir: "{{ zuul.projects['opendev.org/zuul/zuul-operator'].src_dir }}"

    - name: Setup Operator
      command: kubectl create -f deploy/operator.yaml
      args:
        chdir: "{{ zuul.projects['opendev.org/zuul/zuul-operator'].src_dir }}"