- name: install and start zuul operator
  hosts: all

  tasks:
    - name: Set Operator SDK Release Version fact
      set_fact:
        RELEASE_VERSION: v0.8.1

    - name: Setup CRD
      command: kubectl create -f deploy/crds/zuul-ci_v1alpha1_zuul_crd.yaml
      args:
        chdir: "{{ zuul.projects['opendev.org/zuul/zuul-operator'].src_dir }}"

    - name: Setup rbac
      command: kubectl create -f deploy/rbac.yaml
      args:
        chdir: "{{ zuul.projects['opendev.org/zuul/zuul-operator'].src_dir }}"

    - name: Setup Operator
      command: kubectl create -f deploy/operator.yaml
      args:
        chdir: "{{ zuul.projects['opendev.org/zuul/zuul-operator'].src_dir }}"

    - name: wait for pods to come up
      command: kubectl get pods -o json
      register: kubectl_get_pods
      until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
      retries: 30
      delay: 10