---
- name: Apply Zuul CR
  k8s:
    namespace: "{{ namespace }}"
    definition:
      apiVersion: operator.zuul-ci.org/v1alpha1
      kind: Zuul
      metadata:
        name: zuul
      spec: "{{ spec }}"
