
- name: setup gitconfig
  shell: |
    if ! test -f ~/.gitconfig && ! test -d ~/.config/git ; then
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
    fi
    sudo mkdir -p /srv/git

- name: setup local-git service
  become: yes
  copy:
    dest: /etc/systemd/system/local-git.service
    content: |
      [Unit]
      Description=local git service
      After=syslogp.target network.target

      [Service]
      Type=simple
      SyslogIdentifier=local-git
      ExecStart=/usr/bin/git daemon --export-all --reuseaddr --verbose --base-path=/srv/git/ /srv/git/
      Restart=always
      RestartSec=3s

      [Install]
      WantedBy=multi-user.target

- name: start local-git service
  become: yes
  systemd:
    daemon_reload: true
    name: "local-git"
    state: started
