- k8s:
    namespace: default
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: zuul-test-ingress
      spec:
        rules:
        - http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: zuul-web
                  port:
                    number: 9000
