- k8s:
    namespace: default
    definition:
      apiVersion: networking.k8s.io/v1beta1
      kind: Ingress
      metadata:
        name: zuul-test-ingress
      spec:
        rules:
        - http:
            paths:
            - path: /
              backend:
                serviceName: zuul-web
                servicePort: 9000
