- k8s:
    namespace: default
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: test-registry
      spec:
        template:
          spec:
            containers:
            - name: test-registry
              image: quay.io/containers/podman:latest
              command: ['podman', 'login', '--tls-verify=false', 'https://zuul-registry/', '-u', 'testuser', '-p', 'testpass']
              securityContext:
                privileged: true
            restartPolicy: Never
        backoffLimit: 4
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Complete
      status: "True"
